site_name: Hemanth C (Hems)
site_url: https://hemanthvenki910.github.io/Personal-website/
site_author: Hemanth C

theme:
  name: material
  logo: 'artifacts/website/home.png'
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - toc.follow
  palette:
    # Scheme 1: Default to Light Mode
    - scheme: default
      primary: amber
      accent: black
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Scheme 2: Dark Mode
    - scheme: slate
      primary: amber
      accent: white
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  font:
    text: Merriweather
    code: Fira Code

nav:
  - Home: index.md
  - Experience: components/experience.md
  - Projects: components/projects.md
  - Skills: components/skills.md
  - Education: components/education.md

markdown_extensions:
  - attr_list
  - admonition
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.details

